package models

type BaseDocumentReference struct {
	textTitle				string	// Text title of the resource (FHIR text is xhtml) filed by a practitioner or device
	language               string	// Language of the document
	status                 string 	// Fix to "current" when creating (other are: superseded, entered-in-error)
	docStatus              string 	// Fixed to "final" (other are: preliminary, amended, entered-in-error)
	categorySNOMED         string	// The health history section goes to array[0], e.g. "11369-6" (History of Immunization)
	date                   string	// When the document was created
	fileMimeType           string   // e.g. application/pdf
	fileHexSHA1            string   // Legacy SHA1 digest in hexadecimal (FHIR Attachment is BASE64 SHA1)
	fileSize               int      // Number of bytes of content
	typeLOINC              string   // Kind of document or Health Section, e.g.: "48765-2" (Allergies and adverse reactions Document)
	contextPeriodStart     string   // FHIR dateTime: time of service that is being documented
	contextPeriodEnd       string   // FHIR dateTime: end of time service that is being documented
	contentFormatCodeSet   string   // e.g. "urn:ihe:pcc:xphr:2007" or "urn:ihe:pcc:ic:2008"
	facilitySNOMED         string   // Kind of facility where patient was seen
	practiceSettingSNOMED  string   // Clinical Specialty: details about where the content was created
	// securityLabelsFHIR     []string // Document security-tags
	description            string   // Description generated by Practitioner / Device
	subjectUHC             string   // Who/what is the subject of the document
	// authorsReference       []string	// Who and/or what authored the document
	authenticatorReference string	// Who/what authenticated the document
	custodianReference     string 	// Organization which maintains the document
}